// Script to update all HTML pages with proper navigation and mock data
// This is a Node.js script to help update all pages at once

const fs = require('fs');
const path = require('path');

// List of all HTML pages to update
const pages = [
    'about.html',
    'services.html',
    'contact.html',
    'gallery.html',
    'team.html',
    'signup.html',
    'dashboard.html',
    'loading.html',
    'checkout.html',
    'success.html',
    'cart.html'
];

// Function to update a single page
function updatePage(pageName) {
    const filePath = path.join(__dirname, pageName);
    
    if (!fs.existsSync(filePath)) {
        console.log(`Page ${pageName} not found, skipping...`);
        return;
    }
    
    let content = fs.readFileSync(filePath, 'utf8');
    
    // Check if page already has the scripts
    if (content.includes('js/mockdata.js')) {
        console.log(`Page ${pageName} already updated, skipping...`);
        return;
    }
    
    // Add footer before closing body tag
    if (!content.includes('<footer class="footer">')) {
        content = content.replace(
            /<\/body>/,
            `    <!-- Footer -->
    <footer class="footer">
        <!-- Footer content will be generated by navigation.js -->
    </footer>

</body>`
        );
    }
    
    // Add scripts before closing body tag
    content = content.replace(
        /<\/body>/,
        `    <!-- JavaScript -->
    <script src="js/mockdata.js"></script>
    <script src="js/navigation.js"></script>
    <script src="js/main.js"></script>
</body>`
    );
    
    // Write updated content back to file
    fs.writeFileSync(filePath, content);
    console.log(`Updated ${pageName}`);
}

// Update all pages
console.log('Updating all HTML pages...');
pages.forEach(updatePage);
console.log('All pages updated successfully!');
